language: node_js
node_js:
  - "10"

env:
  global:
    # - NODE_ENV=production

before_install:
  - pip install --user codecov
  - yarn global add lerna

after_success:
  - codecov

script:
  - yarn install
  - cd packages/api && yarn install && yarn test:api
  # - cd packages/api && yarn test:api