FROM node:10-alpine

WORKDIR /usr/src/app

ENV NODE_ENV=production

RUN yarn global add lerna
RUN yarn global add typescript

COPY ./package.json .
RUN yarn install --no-lockfile

COPY ./packages/api /usr/src/app/packages/api
EXPOSE 9000 9229

COPY lerna.json .
COPY tsconfig.json .
RUN lerna bootstrap

COPY ./packages/api/lib /usr/src/app/packages/api/lib

CMD cd ./packages/api && yarn start:api