FROM node:10-alpine

WORKDIR /usr/src/app

RUN yarn global add lerna

COPY ./package.json .
RUN yarn install --no-lockfile

COPY ./packages/client /usr/src/app/packages/client
EXPOSE 3000

COPY lerna.json .
RUN lerna bootstrap

CMD yarn start