version: '3.7'
services:
  db:
    image: mongo
    container_name: mars-rover_db
    restart: always
    ports:
      - 2020:27017
    environment:
      MONGO_INITDB_DATABASE: mars-rovers
    command: --smallfiles

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.api
  #   container_name: mars-rover_api
  #   depends_on:
  #     - db
  #   ports:
  #     - 9000:9000
  #     - 9229:9229
  #   volumes:
  #     - ./packages/api/package.json:/usr/src/app/packages/api/package.json
  #     - ./packages/api:/usr/src/app/packages/api
  #     - /usr/src/app/packages/api/node_modules

  # client:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.client
  #   container_name: mars-rover_client
  #   depends_on:
  #     - api
  #   ports:
  #     - "3040:3000"
  #   volumes:
  #     - ./packages/client/package.json:/usr/src/app/packages/client/package.json
  #     - ./packages/client:/usr/src/app/packages/client
  #     - /usr/src/app/packages/client/node_modules