FROM node:10-alpine

WORKDIR /usr/src/app

ENV NODE_ENV=production

RUN yarn global add lerna

COPY ./package.json .
RUN yarn install --no-lockfile

COPY ./packages/api /usr/src/app/packages/api
EXPOSE 9000 9229

COPY lerna.json .
RUN lerna bootstrap

CMD ["yarn", "tsc"]